# Builtin and operators
Quelques demos d'implementation de builtins (`str`, `repr`, `bool`) et opérateurs (`==`, `+`, `-`)
sur des types de Python et de numpy

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
villes = ['Lyon', 'Toulouse', 'Balma', 'Pau']
ville = {
    'nom': 'Toulouse',
    'population': 500_000,
    'code_postal': '31000'
}
dicton = 'Le blé semé le jour de Saint-Bruno devient noir.'
data = np.random.normal(10.0, 2.5, 10_000)

## Str vs Repr

In [3]:
print(dicton)
dicton

Le blé semé le jour de Saint-Bruno devient noir.


'Le blé semé le jour de Saint-Bruno devient noir.'

In [4]:
print(ville['code_postal']) # => str() / __str__
ville['code_postal'] # => repr() / __repr__

31000


'31000'

In [5]:
print(villes)
villes

['Lyon', 'Toulouse', 'Balma', 'Pau']


['Lyon', 'Toulouse', 'Balma', 'Pau']

In [6]:
print(data)
data

[13.5245421   6.12420583  7.52374965 ... 15.24866156 10.29649111
 10.26612042]


array([13.5245421 ,  6.12420583,  7.52374965, ..., 15.24866156,
       10.29649111, 10.26612042], shape=(10000,))

In [7]:
dt = datetime.now()
print(dt)
dt

2025-10-07 17:29:03.230180


datetime.datetime(2025, 10, 7, 17, 29, 3, 230180)

## Repr des DataFrames
NB: ici le hook classique Python `__repr__` est mis en sourdine pour lui privilégier un hook jupyter `_repr_html_` 

In [8]:
df = pd.DataFrame(
    [
        ['Lyon', 500_000, '69000'],
        ['Toulouse', 500_000, '31000'],
    ],
    columns=['Nom', 'Population', 'Code_postal']
)
df

Nom  Population Code_postal
0      Lyon      500000       69000
1  Toulouse      500000       31000

In [9]:
df.__repr__()

'        Nom  Population Code_postal\n0      Lyon      500000       69000\n1  Toulouse      500000       31000'

In [10]:
df._repr_html_()

'<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Nom</th>\n      <th>Population</th>\n      <th>Code_postal</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Lyon</td>\n      <td>500000</td>\n      <td>69000</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Toulouse</td>\n      <td>500000</td>\n      <td>31000</td>\n    </tr>\n  </tbody>\n</table>\n</div>'

## Truth values

In [11]:
assert not []
assert not ''
assert not None # None always False
assert not False
assert not 0

In [12]:
assert [1, 2]
assert 'texte non vide'
assert True
assert 1

In [13]:
type(None)

NoneType

## Egalité hétérogène

In [14]:
assert not 123 == 'a text'
assert not 'a text' == 123

In [15]:
x = 123
x.__eq__('a text')

NotImplemented

In [16]:
'a text'.__eq__(x)

NotImplemented

In [17]:
t = np.array([1, 2, 3, 4])
t

array([1, 2, 3, 4])

In [18]:
t == t

array([ True,  True,  True,  True])

In [19]:
t == 1

array([ True, False, False, False])

In [20]:
1 == t

array([ True, False, False, False])

In [21]:
x = 1
x.__eq__(t)

NotImplemented

In [22]:
t.__eq__(x)

array([ True, False, False, False])

In [23]:
t + t

array([2, 4, 6, 8])

In [24]:
1 - t # __rsub__

array([ 0, -1, -2, -3])

In [25]:
t += 2 # __iadd

In [26]:
t

array([3, 4, 5, 6])

In [27]:
t.shape

(4,)

In [28]:
t.shape = (2,2)
t

array([[3, 4],
       [5, 6]])

In [29]:
# ValueError: cannot reshape array of size 4 into shape (2,3)
# t.shape = (2,3)

In [30]:
# del t.shape

## Operations inplace
- si implementée (`__iadd__`, `__isub__`, ...) => optimisation mémoire
  Exemple: ndarray, list
- sinon il suffit d'avoir l'operation classique (pas inplace) et Python décompose l'appel
     ```
     a += b   =>  a = a + b
     ```
  Exemple: str, tuple

In [31]:
ref = villes
villes += ['Marseille', 'Paris']
villes

['Lyon', 'Toulouse', 'Balma', 'Pau', 'Marseille', 'Paris']

In [32]:
assert ref is villes

In [33]:
shape = (12, 3)
ref = shape
shape += (7, 12)
shape

(12, 3, 7, 12)

In [34]:
assert shape is not ref

In [35]:
sorted([7, 3, 4],  reverse=True)

[7, 4, 3]

## Class method

In [36]:
# object method
t.sum()

np.int64(18)

In [37]:
# class method
dt = datetime.now()
dt

datetime.datetime(2025, 10, 7, 17, 29, 3, 492778)

In [38]:
# constructor (__init__)
datetime(2025, 10, 7, 15, 31, 41, 673952)

datetime.datetime(2025, 10, 7, 15, 31, 41, 673952)

In [39]:
# object method
dt.strftime('%d/%m/%Y')

'07/10/2025'

In [40]:
# class method
datetime.fromisoformat('2025-10-25 11:30')

datetime.datetime(2025, 10, 25, 11, 30)