# Builtin and operators
Quelques demos d'implementation de builtins (`str`, `repr`, `bool`) et opérateurs (`==`, `+`, `-`)
sur des types de Python et de numpy

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
villes = ['Lyon', 'Toulouse', 'Balma', 'Pau']
ville = {
    'nom': 'Toulouse',
    'population': 500_000,
    'code_postal': '31000'
}
dicton = 'Le blé semé le jour de Saint-Bruno devient noir.'
data = np.random.normal(10.0, 2.5, 10_000)

## Str vs Repr

In [3]:
print(dicton)
dicton

Le blé semé le jour de Saint-Bruno devient noir.


'Le blé semé le jour de Saint-Bruno devient noir.'

In [4]:
print(ville['code_postal']) # => str() / __str__
ville['code_postal'] # => repr() / __repr__

31000


'31000'

In [5]:
print(villes)
villes

['Lyon', 'Toulouse', 'Balma', 'Pau']


['Lyon', 'Toulouse', 'Balma', 'Pau']

In [6]:
print(data)
data

[ 8.05462601 11.00147452 16.48598166 ... 13.70103592 11.87044202
  8.38700254]


array([ 8.05462601, 11.00147452, 16.48598166, ..., 13.70103592,
       11.87044202,  8.38700254], shape=(10000,))

In [7]:
dt = datetime.now()
print(dt)
dt

2025-10-06 17:53:14.852266


datetime.datetime(2025, 10, 6, 17, 53, 14, 852266)

## Repr des DataFrames
NB: ici le hook classique Python `__repr__` est mis en sourdine pour lui privilégier un hook jupyter `_repr_html_` 

In [8]:
df = pd.DataFrame(
    [
        ['Lyon', 500_000, '69000'],
        ['Toulouse', 500_000, '31000'],
    ],
    columns=['Nom', 'Population', 'Code_postal']
)
df

Nom  Population Code_postal
0      Lyon      500000       69000
1  Toulouse      500000       31000

In [9]:
df.__repr__()

'        Nom  Population Code_postal\n0      Lyon      500000       69000\n1  Toulouse      500000       31000'

In [10]:
df._repr_html_()

'<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Nom</th>\n      <th>Population</th>\n      <th>Code_postal</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Lyon</td>\n      <td>500000</td>\n      <td>69000</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Toulouse</td>\n      <td>500000</td>\n      <td>31000</td>\n    </tr>\n  </tbody>\n</table>\n</div>'

## Truth values

In [11]:
assert not []
assert not ''
assert not None # None always False
assert not False
assert not 0

In [12]:
assert [1, 2]
assert 'texte non vide'
assert True
assert 1

In [13]:
type(None)

NoneType

## Egalité hétérogène

In [14]:
assert not 123 == 'a text'
assert not 'a text' == 123

In [15]:
x = 123
x.__eq__('a text')

NotImplemented

In [16]:
'a text'.__eq__(x)

NotImplemented

In [17]:
t = np.array([1, 2, 3])
t

array([1, 2, 3])

In [18]:
t == t

array([ True,  True,  True])

In [19]:
t == 1

array([ True, False, False])

In [20]:
1 == t

array([ True, False, False])

In [21]:
x = 1
x.__eq__(t)

NotImplemented

In [22]:
t.__eq__(x)

array([ True, False, False])

In [23]:
t + t

array([2, 4, 6])

In [24]:
1 - t # __rsub__

array([ 0, -1, -2])

In [25]:
t += 2 # __iadd

In [26]:
t

array([3, 4, 5])